{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "session-converter.serviceAccountName" . }}
  labels:
{{ include "session-converter.labels" . | nindent 4 }}
{{- end -}}
