---

- name: Create download dir
  file:
    path: /opt/downloads/cstrike
    state: directory

- name: Copy rpm file
  shell: "/usr/bin/aws s3 sync s3://aws-{{ cloud }}-gh-infrastructure/infrastructure/crowdstrike/linux/ /opt/downloads/cstrike/ --exclude \"*\" --include \"falcon-sensor-5.16*\""

- name: Install falcon rpm
  shell: "yum install -y /opt/downloads/cstrike/falcon-sensor-5.16*"

- name: Run Falcon Sensor
  shell: "/opt/CrowdStrike/falconctl -s --aph={{ proxy }} --app=8080 -s --cid=***-47"

- name: Check that CrowdStrike service is enabled and running
  service:
    name: falcon-sensor
    enabled: yes
    state: started
