---

- name: Install SNMPd
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - "net-snmp"
  - "net-snmp-utils"

- name: Configure SNMP
  shell: net-snmp-create-v3-user -ro -A W1l3yS0lar -a SHA -X S0larWind123 -x AES S0larWind

- name: Disable SNMP v1 and v2
  replace:
    path: /etc/snmp/snmpd.conf
    regexp: '^group   notConfigGroup '
    replace: '#group   notConfigGroup '

- name: Start SNMPd service
  service:
    name: snmpd
    state: started
    enabled: yes