---
# tasks file for httpd
- name: map httpd logs directory
  file:
    src: /opt/logs
    dest: /var/log/httpd
    state: link

- name: install Apache tools
  yum:
    name: httpd
    state: latest

- name: enable logrotate
  copy:
    src: httpd-logrotate
    dest: /etc/logrotate.d/httpd

- name: set read access for tester user
  shell: setfacl -m u:tester:rx /opt/logs
  ignore_errors: yes

- name: add proxy config
  copy:
    src: "proxy.conf.{{ env }}"
    dest: /etc/httpd/conf.d/proxy.conf

- name: add headers config
  copy:
    src: "headers.conf.{{ env }}"
    dest: /etc/httpd/conf.d/headers.conf

- name: enable and start Apache
  service:
    name: httpd
    state: restarted
    enabled: yes
