---
- name: Install OpenJDK 11
  yum:
    name: java-11-openjdk-devel
    state: present
  when:
    - ansible_distribution == "CentOS"

- name: Install OpenJDK 11
  yum:
    name: java-11-openjdk-devel
    enablerepo: rhui-REGION-rhel-server-optional
    state: present
  when:
    - ansible_distribution == "RedHat"
