{{- if .Values.global.istio.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "report-controller.fullname" . }}
  labels:
    {{- include "report-controller.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ .Values.global.hosts.uri | quote }}
  gateways:
    - {{ .Values.global.istio.gatewayName }}
    - mesh
  http:  
  - match:
    - uri:
        prefix: /arg-report-controller/
    - uri:
        prefix: /arg-report-controller
    rewrite:
      uri: "/"
    route:
    - destination:
        host: {{ include "report-controller.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
{{- end }}
