apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "wel-arg.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.global.mail_secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
  {{- range $key, $val := .Values.global.rabbit_secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
  {{- range $key, $val := .Values.global.calc_rabbit_secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
  {{- range $key, $val := .Values.global.db_arg_secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
  {{- range $key, $val := .Values.global.db_pv5_secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
  {{- range $key, $val := .Values.global.db_statistic_secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
