apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calc-service.fullname" . }}
  labels:
    {{- include "calc-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "calc-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calc-service.selectorLabels" . | nindent 8 }}
    {{- if .Values.global.ingress.enabled }}
      annotations:
        sidecar.istio.io/inject: "false"
    {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "calc-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          {{- if .Values.global.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.image.livenessPath }}
              port: http
            failureThreshold: 5
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: {{ .Values.image.livenessPath }}
              port: http
            failureThreshold: 15
            periodSeconds: 10
          {{- end }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ tpl ($val | toString) $ | quote }}
            {{- end }}
            {{- range $key, $val := .Values.global.db_arg_variables }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- range $key, $val := .Values.global.db_arg_secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}
                  key: {{ $key }}
            {{- end }}           
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
